version: '3.4'

services:
  db:
    image: postgres:12.2
    environment:
      - POSTGRES_DB=pco_dashboard
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data

  web:
    build: .
    restart: on-failure
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=ecto://postgres:postgres@db/pco_dashboard
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PORT=4000

volumes:
  db-data:
